version: '3.8'

services:
  form-builder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: dnd-vue-form-builder
